version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: reqres_db
    restart: always
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
